### ISSUE TITLE
Cannot add functionality to Button Component

### ISSUE THREAD

**Issue by ruucm** [harbor-school/HSDS#2]
Share your thoughts of how component users add functionality to this button

@oneybee

https://www.loom.com/share/71239493605c4488bcd8c73b147f8e8c

**Comment by oneybee** [comment]
Fix button component to can add onClick function. #11 

`<Button onClick={()=>{alert('sss')}} />`

**Comment by ruucm** [comment]
@oneybee 

I merged it and closed this issue
