### ISSUE TITLE
Image is cropped in MainHeader comp

### ISSUE THREAD

**Issue by ruucm** [harbor-school/HSDS#4]
Please set background CSS properly
@oneybee

https://www.loom.com/share/da2a3fff155146518265697cad1341c5?focus_title=1&muted=1

**Comment by oneybee** [comment]
Update component using `background-size: contain`

**Comment by oneybee** [comment]
Update component using `background-size: contain`

**Comment by ruucm** [comment]
> Update component using `background-size: contain`

Make a Pull Request using that commits

**Comment by oneybee** [comment]
@ruucm 

Pull Request #5 

Update component using `background-size: contain`

**Comment by ruucm** [comment]
@oneybee 

I can't merge this PR cause you add unrelated commits on here

**Comment by oneybee** [comment]
#16 
add background-size property to MainHeader

**Comment by ruucm** [comment]
@oneybee 

good. I merged #16  and closed this issue
