### ISSUE TITLE
colors from canvas make build err

### ISSUE THREAD

**Issue by ruucm** [harbor-school/HSDS#6]
@framer/ruucm.hsds package version: 1.39.0

After update @framer/ruucm.hsds package to 1.39.0

I can't build the project 

I think cause @oneybee use colors from `canvas` without caring about serverside build

@oneybee. Update your thoughts here

**Comment by oneybee** [comment]
Delete colors from canvas for build test.

I'll check the color and canvas issues after the build test. #7

**Comment by ruucm** [comment]
@oneybee 

I merged #7 

But, It still has a build error 
Check the logs below

```
WebpackError: ReferenceError: window is not defined
  
  - framer.js:1 Object../node_modules/framer/build/framer.js
    node_modules/framer/build/framer.js:1:239
  
  - Spacing.tsx:1 Module../node_modules/@framer/ruucm.hsds/code/Spacing.tsx
    node_modules/@framer/ruucm.hsds/code/Spacing.tsx:1:1
  
  - MainHeader.tsx:1 Module../node_modules/@framer/ruucm.hsds/code/MainHeader.tsx
    node_modules/@framer/ruucm.hsds/code/MainHeader.tsx:1:1
  
  - index.js:1 Module../src/pages/index.js
    src/pages/index.js:1:1
```

**Comment by ruucm** [comment]
@oneybee

**Comment by oneybee** [comment]
Ok, I'll check log and delete unused comments.

**Comment by oneybee** [comment]
#8 
Delete some unused codes and check logs again.

**Comment by oneybee** [comment]
#10 
change canvas colors to colors.js file.
It's not from the canvas so, it can be build.

**Comment by oneybee** [comment]
Wrapping spacing component with isClient for fix build err.
#12

**Comment by oneybee** [comment]
#8 
Wrapping Spacing component with isClient for avoiding build err

**Comment by ruucm** [comment]
@oneybee 


Build success!

You resolve errors 🎉 🎉
